### Creates a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "A for Apple now creates billing account and consumes kafka",
  "address": "Manchester",
  "email": "a@c_newe.com",
  "dateOfBirth": "2004-12-12",
  "registeredDate": "2009-12-25"
}

###